### ISSUE TITLE
Add comments to each blog post

### ISSUE THREAD

**Issue by Vrindagupta6828** [harsh-9in/Blogger#206]
Users can write their views regarding a specific blog by commenting on that blog.

I would like to add this comment option on each blog created.

**Comment by harsh-9in** [comment]
go ahead @Vrindagupta6828 :+1:

**Comment by Vrindagupta6828** [comment]
@harsh-9in Please give me points for raising this issue.

**Comment by chehak123** [comment]
I would like to work on this issue under devscript winter of code

**Comment by harsh-9in** [comment]
This issue is already solved

**Comment by Vrindagupta6828** [comment]
@harsh-9in No it is not solved I was wrking on it and have faced issues and you were guiding me were you able to solve the issue?

**Comment by Vrindagupta6828** [comment]
@harsh-9in Please provide this issue label of it's dificulty
